import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#282b51',
        'on-secondary-container': '#005a3c',
        'primary-fixed': '#7b9cff',
        'on-background': '#282b51',
        'on-tertiary': '#ffeef8',
        'surface-tint': '#0050d4',
        'on-error-container': '#570008',
        'surface': '#f8f5ff',
        'on-tertiary-container': '#661466',
        'outline-variant': '#a7aad7',
        'error': '#b31b25',
        'on-secondary': '#c8ffe0',
        'on-primary-container': '#001e5a',
        'tertiary-container': '#fe9cf4',
        'primary-fixed-dim': '#658eff',
        'on-tertiary-fixed': '#480049',
        'surface-dim': '#cfd1ff',
        'error-container': '#fb5151',
        'secondary-container': '#69f6b8',
        'surface-variant': '#d9daff',
        'inverse-surface': '#06092f',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#000000',
        'background': '#f8f5ff',
        'surface-container-low': '#f1efff',
        'surface-container-highest': '#d9daff',
        'on-error': '#ffefee',
        'primary-container': '#7b9cff',
        'on-surface-variant': '#555881',
        'error-dim': '#9f0519',
        'primary': '#0050d4',
        'inverse-primary': '#618bff',
        'primary-dim': '#0046bb',
        'on-primary': '#f1f2ff',
        'secondary-fixed': '#69f6b8',
        'surface-container-high': '#e0e0ff',
        'tertiary': '#8e3a8a',
        'surface-bright': '#f8f5ff',
        'secondary': '#006947',
        'tertiary-dim': '#802d7d',
        'inverse-on-surface': '#979ac6',
        'outline': '#71749e',
        'surface-container': '#e7e6ff',
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
